'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Alert,AlertDescription } from '@/components/ui/alert'
import { Loader2,Save,RefreshCw,AlertTriangle } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { getExecutionState,queueProgressOffline,submitProgressEvent } from '@/lib/execution-client'
import { isOnline } from '@/lib/api-client'

export function ExecutionProgressScreen({project,orgId,onRefresh}:{project:any|null;orgId:string;onRefresh:()=>void}){
 const {toast}=useToast();const [values,setValues]=useState<Record<string,number>>({});const [versions,setVersions]=useState<Record<string,number>>({});const [busy,setBusy]=useState(false);const [rework,setRework]=useState<{key:string;unitId:number;boqId:number;current:number;next:number}|null>(null);const [reason,setReason]=useState('')
 const rows=useMemo(()=>project?.units?.flatMap((u:any)=> (u.boqItems||[]).map((b:any)=>({unit:u,boq:b,key:`${u.id}:${b.id}`})))||[],[project])
 const load=useCallback(async()=>{if(!rows.length)return;const next:{[k:string]:number}={};const vers:{[k:string]:number}={};for(const r of rows){const s=await getExecutionState(Number(r.unit.id),Number(r.boq.id));next[r.key]=s?.completion_pct??r.boq.completionPct??0;vers[r.key]=s?.state_version??1}setValues(next);setVersions(vers)},[rows])
 useEffect(()=>{load()},[load])
 async function save(key:string,unitId:number,boqId:number,next:number){const current=values[key]??0;if(next===current)return;if(next<current){setRework({key,unitId,boqId,current,next});return}setBusy(true);try{await submitProgressEvent({unitId,boqItemId:boqId,expectedVersion:versions[key]||1,completionPct:next,currentPct:current});setValues(v=>({...v,[key]:next}));await load();onRefresh();toast({title:'تم تسجيل تقدم التنفيذ'})}catch(e){if(!isOnline()){await queueProgressOffline(orgId,{unitId:String(unitId),boqItemId:String(boqId),completionPct:next,reworkFlag:false,reworkReason:''});setValues(v=>({...v,[key]:next}));toast({title:'حُفظ محلياً',description:'سيتم إرساله عند عودة الاتصال'})}else toast({title:'فشل تسجيل التقدم',description:String(e),variant:'destructive'})}finally{setBusy(false)}}
 async function confirmRework(){if(!rework||reason.trim().length<20)return;setBusy(true);try{await submitProgressEvent({unitId:rework.unitId,boqItemId:rework.boqId,expectedVersion:versions[rework.key]||1,completionPct:rework.next,currentPct:rework.current,reworkReason:reason});setRework(null);setReason('');await load();onRefresh();toast({title:'تم تسجيل إعادة التنفيذ'})}catch(e){toast({title:'تعذر تسجيل إعادة التنفيذ',description:String(e),variant:'destructive'})}finally{setBusy(false)}}
 if(!project)return <Card className="border-dashed"><CardContent className="p-10 text-center text-gray-500">اختر مشروعاً لبدء تسجيل التنفيذ</CardContent></Card>
 return <div className="space-y-4"><Alert><AlertTriangle className="w-4 h-4"/><AlertDescription>التعديلات تمر عبر Event Pipeline مع Optimistic Locking. خفض الإنجاز يتطلب سبب إعادة تنفيذ لا يقل عن 20 حرفاً.</AlertDescription></Alert><div className="flex justify-between items-center"><div><h2 className="text-2xl font-bold">تنفيذ الأعمال</h2><p className="text-sm text-gray-500">تسجيل التقدم الفعلي للمشروع: {project.name}</p></div><Button variant="outline" onClick={load} disabled={busy}><RefreshCw className={busy?'animate-spin':''}/></Button></div><Card><CardHeader><CardTitle className="text-base">بنود الكميات</CardTitle></CardHeader><CardContent><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-2">الوحدة</th><th>البند</th><th>الكمية</th><th>الإنجاز %</th><th>حفظ</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.key} className="border-b"><td className="p-2">{r.unit.name}</td><td>{r.boq.description}</td><td>{r.boq.quantity} {r.boq.unitOfMeasure}</td><td><Input type="number" min="0" max="100" className="w-24" value={values[r.key]??0} onChange={e=>setValues(v=>({...v,[r.key]:Math.max(0,Math.min(100,Number(e.target.value)||0))}))}/></td><td><Button size="sm" disabled={busy} onClick={()=>save(r.key,Number(r.unit.id),Number(r.boq.id),values[r.key]??0)}><Save className="ml-1 w-4 h-4"/>حفظ</Button></td></tr>)}</tbody></table></div></CardContent></Card><Dialog open={!!rework} onOpenChange={v=>!v&&setRework(null)}><DialogContent><DialogHeader><DialogTitle>تأكيد إعادة التنفيذ</DialogTitle></DialogHeader><div className="space-y-3"><p className="text-sm">سيتم خفض الإنجاز من {rework?.current}% إلى {rework?.next}%.</p><Label>سبب إعادة التنفيذ — 20 حرفاً على الأقل</Label><Textarea value={reason} onChange={e=>setReason(e.target.value)} /><p className="text-xs text-gray-500">{reason.trim().length}/20</p></div><DialogFooter><Button variant="outline" onClick={()=>setRework(null)}>إلغاء</Button><Button disabled={busy||reason.trim().length<20} onClick={confirmRework}>تأكيد</Button></DialogFooter></DialogContent></Dialog></div>
}
