'use client'
import {useEffect,useState} from 'react'
import {CalendarDays,MapPin,Save,WifiOff,RefreshCw} from 'lucide-react'
import {Button} from '@/components/ui/button';import {Badge} from '@/components/ui/badge';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {useToast} from '@/hooks/use-toast';import {listDiary,saveDiary,type DiaryEntry} from '@/lib/legacy-capabilities-api'
export function FieldDiaryScreen({projectId,projectName}:{projectId?:string;projectName?:string}){const{toast}=useToast();const[entries,setEntries]=useState<DiaryEntry[]>([]);const[loading,setLoading]=useState(false);const[online,setOnline]=useState(true);const[form,setForm]=useState({diary_date:new Date().toISOString().slice(0,10),weather:'',workers:'',equipment:'',visits_total:'0',visits_accepted:'0',observations:'',gps_tag:null as Record<string,unknown>|null});
const load=async()=>{if(!projectId)return;setLoading(true);try{setEntries((await listDiary(projectId)).items)}catch(e){console.warn(e)}finally{setLoading(false)}};useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);useEffect(()=>{load()},[projectId]);
const gps=()=>navigator.geolocation?.getCurrentPosition(p=>setForm(f=>({...f,gps_tag:{lat:p.coords.latitude,lng:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date().toISOString()}})),()=>toast({title:'تعذر الحصول على الموقع',variant:'destructive'}));
const save=async()=>{if(!projectId)return;const payload={project_id:Number(projectId),diary_date:form.diary_date,weather:form.weather||null,workforce:{workers:Number(form.workers||0)},equipment:form.equipment.split(',').map(s=>s.trim()).filter(Boolean),visits_total:Number(form.visits_total||0),visits_accepted:Number(form.visits_accepted||0),observations:form.observations||null,gps_tag:form.gps_tag,attachments:[]};if(!online){localStorage.setItem('fieldops-diary-draft',JSON.stringify(payload));return toast({title:'تم حفظ المسودة محلياً'})}try{await saveDiary(payload);await load();toast({title:'تم حفظ سجل الموقع'})}catch(e){localStorage.setItem('fieldops-diary-draft',JSON.stringify(payload));toast({title:'تعذر الخادم — حفظت كمسودة',variant:'destructive'})}};
return <div className="space-y-5"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">سجل الموقع اليومي</h2><p className="text-sm text-gray-500">{projectName||'اختر مشروعاً'}</p></div>{!online&&<Badge><WifiOff className="w-3 h-3 ml-1"/>أوفلاين</Badge>}</div><div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2 bg-white border rounded-xl p-5 space-y-4"><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">التاريخ<Input type="date" value={form.diary_date} onChange={e=>setForm({...form,diary_date:e.target.value})}/></label><label className="text-sm">الطقس<Input value={form.weather} onChange={e=>setForm({...form,weather:e.target.value})}/></label><label className="text-sm">عدد العمال<Input type="number" min="0" value={form.workers} onChange={e=>setForm({...form,workers:e.target.value})}/></label><label className="text-sm">المعدات<Input placeholder="معدات مفصولة بفواصل" value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})}/></label><label className="text-sm">إجمالي الزيارات<Input type="number" min="0" value={form.visits_total} onChange={e=>setForm({...form,visits_total:e.target.value})}/></label><label className="text-sm">المقبول<Input type="number" min="0" value={form.visits_accepted} onChange={e=>setForm({...form,visits_accepted:e.target.value})}/></label></div><label className="text-sm">الملاحظات اليومية<Textarea rows={6} value={form.observations} onChange={e=>setForm({...form,observations:e.target.value})}/></label><div className="flex gap-2"><Button variant="outline" onClick={gps}><MapPin className="w-4 h-4 ml-1"/>{form.gps_tag?'تم التقاط GPS':'التقاط GPS'}</Button><Button onClick={save}><Save className="w-4 h-4 ml-1"/>حفظ</Button></div></div><div className="bg-white border rounded-xl p-5"><h3 className="font-bold mb-3">السجل السابق</h3>{loading?<RefreshCw className="animate-spin"/>:entries.length?entries.slice(0,10).map(e=><div key={e.id} className="border rounded-lg p-3 mb-2"><div className="flex justify-between text-sm"><b>{e.diary_date}</b><span>{e.visits_accepted}/{e.visits_total}</span></div><p className="text-xs text-gray-600 mt-1">{e.observations||'بدون ملاحظات'}</p></div>):<p className="text-sm text-gray-500">لا توجد سجلات.</p>}</div></div></div>}
