'use client'
import React, { useMemo, useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { AlertTriangle, Loader2, Save, Zap } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { addToSyncQueue } from '@/lib/offline-db'
import { createProgressIntent, submitExecutionEvents } from '@/lib/execution-events'

type Item={id:string;unitId:string;trade:string;completionPct:number;stateVersion?:number}
type Unit={id:string;name:string;code:string;unitType:string;boqItems:Item[]}
export function SpeedEntryGrid({project,onRefresh}:{project:{id:string;name:string;units:Unit[]}|null;orgId:string;onRefresh:()=>void}){
 const {toast}=useToast(); const [values,setValues]=useState<Record<string,number>>({}); const [pending,setPending]=useState<Record<string,{unitId:string;itemId:string;base:number;target:number;version:number;reason?:string}>>({}); const [edit,setEdit]=useState<string|null>(null); const [input,setInput]=useState(''); const [rework,setRework]=useState<any>(null); const [reason,setReason]=useState(''); const [saving,setSaving]=useState(false)
 const trades=useMemo(()=>[...new Set(project?.units.flatMap(u=>u.boqItems.map(i=>i.trade))||[])],[project]);
 const pct=(u:Unit,i:Item)=>values[`${u.id}-${i.id}`]??i.completionPct;
 const stage=(u:Unit,i:Item)=>{const k=`${u.id}-${i.id}`,base=pct(u,i),target=Math.max(0,Math.min(100,Number(input))); if(!Number.isFinite(target))return setEdit(null); const c={unitId:u.id,itemId:i.id,base,target,version:i.stateVersion||1};setEdit(null);if(target<base){setRework(c);setReason('')}else{setValues(v=>({...v,[k]:target}));setPending(p=>({...p,[k]:c}))}}
 const save=async()=>{const changes=Object.values(pending);if(!changes.length)return;setSaving(true);try{if(!navigator.onLine){for(const c of changes)await addToSyncQueue({operationUuid:uuidv4(),entityType:'boqProgress',operationType:'BULK_PROGRESS',endpoint:'/execution/bulk-progress',method:'POST',maxRetries:5,payload:JSON.stringify({unit_id:Number(c.unitId),boq_item_id:Number(c.itemId),completion_pct:c.target,rework_flag:c.target<c.base,rework_reason:c.reason||null})});toast({title:'تم الحفظ محلياً',description:'ستتم المزامنة عند الاتصال.'});setPending({});return}const result=await submitExecutionEvents(changes.map(c=>createProgressIntent({unitId:c.unitId,boqItemId:c.itemId,expectedVersion:c.version,deltaPct:c.target-c.base,rework:c.target<c.base,reason:c.reason})),uuidv4());const failed=result.results.filter(r=>r.event_id==='FAILED'||r.current_state?.error);if(failed.length)throw new Error(`تعذر اعتماد ${failed.length} تغيير`);setPending({});toast({title:'تم الحفظ',description:`اعتمد ${result.results.length} تغيير.`});onRefresh()}catch(e){toast({title:'تعذر الاعتماد',description:e instanceof Error?e.message:'خطأ غير معروف',variant:'destructive'})}finally{setSaving(false)}}
 if(!project)return <div className="flex h-64 items-center justify-center text-gray-500"><Zap className="ml-2"/>اختر مشروعاً</div>
 return <div className="space-y-4"><Alert><AlertTriangle className="h-4 w-4"/><AlertDescription>الإدخال السريع مرتبط الآن بمحرك الأحداث. خفض الإنجاز يتطلب سبب إعادة لا يقل عن 20 حرفاً.</AlertDescription></Alert><div className="flex justify-end"><Button disabled={saving||!Object.keys(pending).length} onClick={save}>{saving?<Loader2 className="ml-2 animate-spin"/>:<Save className="ml-2"/>}حفظ التغييرات ({Object.keys(pending).length})</Button></div><Card><CardContent className="overflow-auto p-0"><table className="w-full text-xs"><thead className="bg-gray-50"><tr><th className="p-3 text-right">الوحدة</th>{trades.map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{project.units.map(u=><tr key={u.id} className="border-t"><td className="p-3"><b>{u.name}</b><div className="text-gray-400">{u.code} • {u.unitType}</div></td>{trades.map(t=>{const i=u.boqItems.find(x=>x.trade===t);if(!i)return <td key={t} className="text-center">—</td>;const k=`${u.id}-${i.id}`,v=pct(u,i);return <td key={t} className="p-2 text-center">{edit===k?<input autoFocus type="number" min="0" max="100" value={input} onChange={e=>setInput(e.target.value)} onBlur={()=>stage(u,i)} onKeyDown={e=>e.key==='Enter'&&stage(u,i)} className="w-16 rounded border p-1 text-center"/>:<button className="rounded bg-gray-100 px-3 py-1" onClick={()=>{setEdit(k);setInput(String(v))}}>{v}%</button>}</td>})}</tr>)}</tbody></table></CardContent></Card><Dialog open={!!rework} onOpenChange={o=>!o&&setRework(null)}><DialogContent><DialogHeader><DialogTitle>سبب إعادة العمل</DialogTitle></DialogHeader><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="اكتب السبب بالتفصيل..."/><div className="text-xs">{reason.trim().length}/20</div><DialogFooter><Button variant="outline" onClick={()=>setRework(null)}>إلغاء</Button><Button disabled={reason.trim().length<20} onClick={()=>{const c={...rework,reason:reason.trim()};setValues(v=>({...v,[`${c.unitId}-${c.itemId}`]:c.target}));setPending(p=>({...p,[`${c.unitId}-${c.itemId}`]:c}));setRework(null)}}>تأكيد</Button></DialogFooter></DialogContent></Dialog></div>
}
