'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Progress } from '@/components/ui/progress'
import { Loader2,Plus,RefreshCw,Search } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { createWorkOrder,listWorkOrders,updateWorkOrder,type WorkOrder } from '@/lib/execution-client'
interface Props { project:any|null; orgId:string; onRefresh:()=>void }
const STATUS:Record<string,string>={DRAFT:'مسودة',PENDING_APPROVAL:'بانتظار الموافقة',APPROVED:'معتمد',IN_PROGRESS:'قيد التنفيذ',COMPLETED:'مكتمل',CANCELLED:'ملغي'}
const PRIORITY:Record<string,string>={LOW:'منخفض',MEDIUM:'متوسط',HIGH:'مرتفع',CRITICAL:'حرج'}
const TYPES:Record<string,string>={CONSTRUCTION:'إنشاء',INSPECTION:'تفتيش',MAINTENANCE:'صيانة',REWORK:'إعادة تنفيذ'}
export function WorkOrdersScreen({project,onRefresh}:Props){
 const {toast}=useToast();const [items,setItems]=useState<WorkOrder[]>([]);const [loading,setLoading]=useState(false);const [loadError,setLoadError]=useState<string|null>(null);const [q,setQ]=useState('');const [status,setStatus]=useState('ALL');const [priority,setPriority]=useState('ALL');const [type,setType]=useState('ALL');const [open,setOpen]=useState(false);const [selected,setSelected]=useState<WorkOrder|null>(null);const [form,setForm]=useState({title:'',description:'',unitId:'',woType:'CONSTRUCTION',priority:'MEDIUM'})
 const load=useCallback(async()=>{if(!project?.id)return;setLoading(true);setLoadError(null);try{const r=await listWorkOrders(project.id);const rows=Array.isArray(r)?r:Array.isArray((r as any)?.items)?(r as any).items:Array.isArray((r as any)?.data?.items)?(r as any).data.items:[];setItems(rows)}catch(e){const message=e instanceof Error?e.message:String(e);setLoadError(message);setItems([]);toast({title:'تعذر تحميل أوامر العمل',description:message,variant:'destructive'})}finally{setLoading(false)}},[project?.id,toast]);useEffect(()=>{load()},[load])
 const filtered=useMemo(()=>items.filter(w=>(status==='ALL'||w.status===status)&&(priority==='ALL'||w.priority===priority)&&(type==='ALL'||w.wo_type===type)&&(!q||`${w.title} ${w.description||''}`.toLowerCase().includes(q.toLowerCase()))),[items,status,priority,type,q]);const stats=useMemo(()=>({total:items.length,inProgress:items.filter(x=>x.status==='IN_PROGRESS').length,completed:items.filter(x=>x.status==='COMPLETED').length,rework:items.filter(x=>x.rework_flag).length,critical:items.filter(x=>x.priority==='CRITICAL').length}),[items])
 async function submitCreate(){if(!project||!form.title.trim()){toast({title:'العنوان مطلوب',variant:'destructive'});return}try{await createWorkOrder({project_id:Number(project.id),unit_id:form.unitId?Number(form.unitId):null,title:form.title.trim(),description:form.description||null,wo_type:form.woType,priority:form.priority});setOpen(false);setForm({title:'',description:'',unitId:'',woType:'CONSTRUCTION',priority:'MEDIUM'});await load();onRefresh();toast({title:'تم إنشاء أمر العمل'})}catch(e){toast({title:'فشل إنشاء أمر العمل',description:String(e),variant:'destructive'})}}
 async function changeStatus(w:WorkOrder,next:string){try{const updated=await updateWorkOrder(w.id,{status:next});setItems(v=>v.map(x=>x.id===w.id?updated:x));setSelected(updated);onRefresh()}catch(e){toast({title:'تعذر تغيير الحالة',description:String(e),variant:'destructive'})}}
 async function changeProgress(w:WorkOrder,pct:number){try{const updated=await updateWorkOrder(w.id,{completion_pct:pct});setItems(v=>v.map(x=>x.id===w.id?updated:x));setSelected(updated);onRefresh()}catch(e){toast({title:'تعذر تحديث الإنجاز',description:String(e),variant:'destructive'})}}
 if(!project)return <Card className="border-dashed"><CardContent className="p-10 text-center text-gray-500">اختر مشروعاً لعرض أوامر العمل</CardContent></Card>
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">أوامر العمل</h2><p className="text-sm text-gray-500">بيانات حقيقية من Execution API — {project.name}</p></div><div className="flex gap-2"><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className={loading?'animate-spin':''}/></Button><Button onClick={()=>setOpen(true)}><Plus className="ml-1"/> أمر عمل جديد</Button></div></div>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['الإجمالي',stats.total],['قيد التنفيذ',stats.inProgress],['مكتمل',stats.completed],['إعادة تنفيذ',stats.rework],['حرج',stats.critical]].map(([l,v])=><Card key={String(l)}><CardContent className="p-4 text-center"><div className="text-xs text-gray-500">{l}</div><div className="text-xl font-bold mt-1">{v}</div></CardContent></Card>)}</div>
 {loadError&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">تعذر تحميل أوامر العمل من الخادم: {loadError}<Button variant="outline" size="sm" className="mr-3" onClick={load} disabled={loading}>إعادة المحاولة</Button></div>}
 <Card><CardContent className="p-4 flex flex-wrap gap-3"><div className="relative flex-1 min-w-[220px]"><Search className="absolute right-3 top-2.5 w-4 h-4 text-gray-400"/><Input className="pr-9" placeholder="بحث..." value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">كل الحالات</SelectItem>{Object.entries(STATUS).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><Select value={priority} onValueChange={setPriority}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">كل الأولويات</SelectItem>{Object.entries(PRIORITY).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><Select value={type} onValueChange={setType}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">كل الأنواع</SelectItem>{Object.entries(TYPES).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></CardContent></Card>
 <Card><CardHeader><CardTitle className="text-base">أوامر العمل الفعلية ({filtered.length})</CardTitle></CardHeader><CardContent>{loading?<div className="p-10 text-center"><Loader2 className="animate-spin mx-auto"/></div>:filtered.length===0?<div className="p-10 text-center text-gray-500">لا توجد أوامر عمل</div>:<div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-2">العنوان</th><th>النوع</th><th>الأولوية</th><th>الحالة</th><th>الإنجاز</th><th></th></tr></thead><tbody>{filtered.map(w=><tr key={w.id} className="border-b hover:bg-gray-50"><td className="p-2 font-medium">{w.title}<div className="text-xs text-gray-400">#{w.id}</div></td><td>{TYPES[w.wo_type]||w.wo_type}</td><td><Badge>{PRIORITY[w.priority]||w.priority}</Badge></td><td><Badge>{STATUS[w.status]||w.status}</Badge></td><td className="min-w-[150px]"><div className="flex items-center gap-2"><Progress value={w.completion_pct} className="w-24"/><span>{Math.round(w.completion_pct)}%</span></div></td><td><Button size="sm" variant="outline" onClick={()=>setSelected(w)}>إدارة</Button></td></tr>)}</tbody></table></div>}</CardContent></Card>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.title}</DialogTitle></DialogHeader>{selected&&<div className="space-y-4"><p className="text-sm text-gray-500">{selected.description||'بدون وصف'}</p><div><Label>الحالة</Label><Select value={selected.status} onValueChange={v=>changeStatus(selected,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(STATUS).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label>الإنجاز</Label><div className="flex gap-2 mt-2 flex-wrap">{[0,25,50,75,100].map(p=><Button key={p} size="sm" variant={selected.completion_pct===p?'default':'outline'} onClick={()=>changeProgress(selected,p)}>{p}%</Button>)}</div></div></div>}</DialogContent></Dialog>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>إنشاء أمر عمل</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>العنوان</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><Label>الوصف</Label><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><Label>الوحدة</Label><Select value={form.unitId||'none'} onValueChange={v=>setForm({...form,unitId:v==='none'?'':v})}><SelectTrigger><SelectValue placeholder="اختياري"/></SelectTrigger><SelectContent><SelectItem value="none">بدون وحدة</SelectItem>{(project.units||[]).map((u:any)=><SelectItem key={u.id} value={String(u.id)}>{u.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-2"><Select value={form.woType} onValueChange={v=>setForm({...form,woType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(TYPES).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><Select value={form.priority} onValueChange={v=>setForm({...form,priority:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(PRIORITY).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button><Button onClick={submitCreate}>حفظ</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
